name: Nickname
author: Taufuu
api: [3.9.3]
version: 1.0
main: Taufuu
# For "main" statement above, find the main class path, but exclude "src"

# Commands: If ur plugin has commands: Do this:
command:
	/nick:
		description: changesnickname
		usage: /nick

# Permissions 
permissions:
	nick.permissons
		default: true
