name: Joinmessage
author: Tofuu
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
version: 1.0
main: plugintest

command:
  nothing:
    description: do absolutly nothing.
    usage: /nothing

permissions:
  nothing.command:
    default: true